In [33]:
#Importez les librairies
import pandas as pd

In [34]:
# Lire le fichier CSV
data = pd.read_csv('Credits_0594.csv', sep = ";", header = 0, index_col = 0)

In [35]:
#Partie À
#Afficher les 5 premières lignes du tableau
data.head()

,Revenu_Annuel,Montant_Credit,Durée_Credit,Taux_Interet,Type_Credit,Statut_Credit
ID_Client,,,,,,
C0001,54535,302034,15,4.43,Consommation,Accepté
C0002,28512,107207,15,5.48,Immobilier,Refusé
C0003,19841,67554,10,2.84,Consommation,Accepté
C0004,93528,87282,5,2.50,Consommation,Refusé
C0005,54261,148088,20,4.77,Consommation,Accepté

In [36]:
#Indiquer les dimensions de ce fichier
data.shape

(100, 6)

In [37]:
#Enumérer les colonnes
data.columns

Index(['Revenu_Annuel', 'Montant_Credit', 'Durée_Credit', 'Taux_Interet',
       'Type_Credit', 'Statut_Credit'],
      dtype='str')

In [51]:
#Spécifier les types de colonnes
t = data.dtypes
t

Revenu_Annuel       int64
Montant_Credit      int64
Durée_Credit        int64
Taux_Interet      float64
Type_Credit           str
Statut_Credit         str
Credit_Annee      float64
dtype: object

In [39]:
#Accéder aux données du "Type_Credit"
data["Type_Credit"]

ID_Client
C0001    Consommation
C0002      Immobilier
C0003    Consommation
C0004    Consommation
C0005    Consommation
             ...
C0096      Immobilier
C0097            Auto
C0098    Consommation
C0099            Auto
C0100      Immobilier
Name: Type_Credit, Length: 100, dtype: str

In [40]:
#Accéder aux données du "Taux_Interet"
data["Taux_Interet"]

ID_Client
C0001    4.43
C0002    5.48
C0003    2.84
C0004    2.50
C0005    4.77
         ...
C0096    3.60
C0097    2.08
C0098    3.59
C0099    3.57
C0100    2.68
Name: Taux_Interet, Length: 100, dtype: float64

In [41]:
#Accéder aux données du "Revenu_Annuel" , "Montant_Credit", Durée_Credit"
data[["Revenu_Annuel", "Montant_Credit", "Durée_Credit"]]

           Revenu_Annuel  Montant_Credit  Durée_Credit
ID_Client
C0001              54535          302034            15
C0002              28512          107207            15
C0003              19841           67554            10
C0004              93528           87282             5
C0005              54261          148088            20
...                  ...             ...           ...
C0096              64805          178598             5
C0097              19196          276994            25
C0098              90997          351522            25
C0099              46114          223449            15
C0100              29029           52149            25

[100 rows x 3 columns]

In [42]:
#Pensez-vous qu’il y a plus Statut_Credit accepte ou refusé ?

In [43]:
#Lister les caractéristiques statistiques des variables Revenu_Annuel" et "Montant_Credit"
data[["Revenu_Annuel", "Montant_Credit"]].describe()

       Revenu_Annuel  Montant_Credit
count     100.000000      100.000000
mean    54859.070000   287293.540000
std     23791.660473   137069.994499
min     15104.000000     7451.000000
25%     34481.750000   188506.750000
50%     51496.500000   302476.000000
75%     73638.000000   395726.250000
max     99146.000000   499561.000000

In [52]:
#Pensez-vous qu’il y a plus Statut_Credit accepte ou refusé ? Analyser en %
data["Statut_Credit"].value_counts(normalize = True)*100

Statut_Credit
Refusé     51
Accepté    49
Name: count, dtype: int64

In [45]:
#Enumérer la première valeur de « Type_Credit »
data["Type_Credit"].head(1)

ID_Client
C0001    Consommation
Name: Type_Credit, dtype: str

In [46]:
#Enumérer les 4 premières valeurs du Durée_Credit
data["Type_Credit"].head(4)

ID_Client
C0001    Consommation
C0002      Immobilier
C0003    Consommation
C0004    Consommation
Name: Type_Credit, dtype: str

In [47]:
#Trier les valeurs du « Taux_Interet » du plus petit au plus grand
data["Taux_Interet"].sort_values()

ID_Client
C0034    1.54
C0032    1.57
C0066    1.60
C0089    1.64
C0063    1.70
         ...
C0050    5.36
C0083    5.38
C0031    5.40
C0002    5.48
C0060    5.49
Name: Taux_Interet, Length: 100, dtype: float64

In [48]:
#Partie B
#Créer une nouvelle colonne dans le dataFrame initiale afin de calculer le montant du crédit par année (diviser le montant du crédit par la durée du crédit)
data["Credit_Annee"]=data["Montant_Credit"]/data['Durée_Credit']
data["Credit_Annee"]

ID_Client
C0001    20135.600000
C0002     7147.133333
C0003     6755.400000
C0004    17456.400000
C0005     7404.400000
             ...
C0096    35719.600000
C0097    11079.760000
C0098    14060.880000
C0099    14896.600000
C0100     2085.960000
Name: Credit_Annee, Length: 100, dtype: float64

In [49]:
#Afficher les données où le montant crédit est > 13 000€ par an
data[(data["Credit_Annee"]>13000)]

,Revenu_Annuel,Montant_Credit,Durée_Credit,Taux_Interet,Type_Credit,Statut_Credit,Credit_Annee
ID_Client,,,,,,,
C0001,54535,302034,15,4.43,Consommation,Accepté,20135.60
C0004,93528,87282,5,2.50,Consommation,Refusé,17456.40
C0008,69729,386621,5,2.74,Immobilier,Accepté,77324.20
C0009,54627,367497,10,4.13,Consommation,Accepté,36749.70
C0012,64725,421507,5,2.84,Immobilier,Refusé,84301.40
...,...,...,...,...,...,...,...
C0094,86256,302918,10,2.21,Consommation,Accepté,30291.80
C0095,34420,182235,10,1.78,Auto,Refusé,18223.50
C0096,64805,178598,5,3.60,Immobilier,Accepté,35719.60
C0098,90997,351522,25,3.59,Consommation,Refusé,14060.88
C0099,46114,223449,15,3.57,Auto,Refusé,14896.60

In [50]:
#Afficher les valeurs du montant_annuel trié par ordre croissant
data["Credit_Annee"].sort_values()

ID_Client
C0089      298.04
C0073      517.80
C0100     2085.96
C0088     2132.40
C0061     3736.40
           ...
C0012    84301.40
C0051    91303.80
C0027    96927.00
C0079    98972.80
C0023    99207.40
Name: Credit_Annee, Length: 100, dtype: float64