# Learning Objectives

Understand the dataset, 
Data preprocessing - Cleaning and Cleansing and 
Data analysis

# Data importation

In [2]:
import heapq
from locale import normalize

# 1. Load the Dataset Titanic built-in in python
import pandas as pd
import seaborn as sns

titanicData = sns.load_dataset("titanic")

In [3]:
# 2. get the size of the dataset
titanicData.shape

(891, 15)

In [4]:
#Show the first 5 rows
titanicData.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
#Show the last 5 rows
titanicData.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
# get the info of the dataset
titanicData.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

# Data Preprocessing

In [7]:
#check missing values
titanicData.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
# manage missing values as you see pertinent

titanicData = titanicData.drop(columns=["deck"])

In [9]:
#check missing values
titanicData.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [10]:
# manage missing values as you see pertinent
titanicData["age"] = titanicData["age"].fillna(titanicData["age"].mean())

In [11]:
# manage missing values as you see pertinent
titanicData["embarked"] = titanicData["embarked"].fillna(titanicData["embarked"].mode()[0])

In [12]:
# manage missing values as you see pertinent
titanicData["embark_town"] = titanicData["embark_town"].fillna("non renseigné")

In [13]:
#check missing values
titanicData.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [14]:
# Check for duplicate rows
print(titanicData.duplicated().sum())

111

In [15]:
#Drop duplicates keeping the first occurance
titanicData = titanicData.drop_duplicates()

In [16]:
# Check for duplicate rows
print(titanicData.duplicated().sum())

0

In [17]:
#show the final dataset 5 first rows
titanicData.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

1. Which columns are numerical? Which are categorical?

# Data Analysis

In [18]:
#Is there more people alive or dead ? Intepret in %
titanicData["alive"].value_counts(normalize=True)*100

alive
no     58.717949
yes    41.282051
Name: proportion, dtype: float64

In [19]:
#group survival status (alive) by embarkation town (embark_town) and calculate both counts and percentages.
titanicData.groupby("embark_town")["alive"].value_counts()

embark_town    alive
Cherbourg      yes       90
               no        65
Queenstown     no        38
               yes       20
Southampton    no       355
               yes      210
non renseigné  yes        2
Name: count, dtype: int64

In [20]:
#The question but in %
titanicData.groupby("embark_town")["alive"].value_counts(normalize=True)*100

embark_town    alive
Cherbourg      yes       58.064516
               no        41.935484
Queenstown     no        65.517241
               yes       34.482759
Southampton    no        62.831858
               yes       37.168142
non renseigné  yes      100.000000
Name: proportion, dtype: float64

In [21]:
#How many classes do we have ?
titanicData["class"].nunique()

3

In [22]:
#Enumerate the different classes
titanicData["class"].unique().tolist()

['Third', 'First', 'Second']

In [23]:
#Is there more man or women embarked in the Titanic. Count the number of men and number of women
titanicData["sex"].value_counts()

sex
male      488
female    292
Name: count, dtype: int64

In [24]:
#analyse your results in %
titanicData["sex"].value_counts(normalize=True)*100

sex
male      62.564103
female    37.435897
Name: proportion, dtype: float64

In [25]:
#What is the maximum age and the minimum age of people embarked ?

In [26]:
#What is the maximum age and the minimum age of people embarked ?
#min
print(titanicData['age'].min())

0.42

In [27]:
#max
print(titanicData['age'].max())

80.0

In [28]:
#What is the average age ?
print(titanicData['age'].mean())

29.797600301659124

In [29]:
#How many embark_town are they ?
titanicData["embark_town"].nunique()

4

In [30]:
##List the embarked towns
titanicData["embark_town"].unique().tolist()

['Southampton', 'Cherbourg', 'Queenstown', 'non renseigné']

### Indexing

### Using .loc[] (Label-based indexing)

In [31]:
#Select all information about the passenger at index 0.
titanicData.loc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [32]:
#Select all information about the passenger at index 50.
titanicData.loc[50]

survived                 0
pclass                   3
sex                   male
age                    7.0
sibsp                    4
parch                    1
fare               39.6875
embarked                 S
class                Third
who                  child
adult_male           False
embark_town    Southampton
alive                   no
alone                False
Name: 50, dtype: object

In [33]:
#Get the sex and age of the passenger at index 10.
titanicData.loc[10,["sex",'age']]

sex    female
age       4.0
Name: 10, dtype: object

In [34]:
#Select passengers from index 100 to 105 and show only their survived and pclass columns.
titanicData.loc[100:105,["survived",'pclass']]

     survived  pclass
100         0       3
102         0       1
103         0       3
104         0       3
105         0       3

In [35]:
#Get all passengers who embarked from "Southampton" and display only sex, age, and fare
titanicData.loc[titanicData['embark_town']=="Southampton", ["sex",'age','fare']]

        sex        age     fare
0      male  22.000000   7.2500
2    female  26.000000   7.9250
3    female  35.000000  53.1000
4      male  35.000000   8.0500
6      male  54.000000  51.8625
..      ...        ...      ...
881    male  33.000000   7.8958
882  female  22.000000  10.5167
883    male  28.000000  10.5000
887  female  19.000000  30.0000
888  female  29.699118  23.4500

[565 rows x 3 columns]

In [36]:
#Select the first 5 female passengers and display their age, pclass, and survived.

### Using .iloc[] (Position-based indexing)

In [37]:
#Display the first row of the dataset.
titanicData.iloc[0]

survived                 0
pclass                   3
sex                   male
age                   22.0
sibsp                    1
parch                    0
fare                  7.25
embarked                 S
class                Third
who                    man
adult_male            True
embark_town    Southampton
alive                   no
alone                False
Name: 0, dtype: object

In [38]:
#Get the values of age and fare for the 5th passenger (row index 4).
titanicData.iloc[4,[3,6]]

age     35.00
fare     8.05
Name: 4, dtype: float64

In [39]:
#Display the first 10 passengers (rows 0–9) but only the first 3 columns (survived, pclass, sex).
titanicData.iloc[0:10,0:3]

   survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female
3         1       1  female
4         0       3    male
5         0       3    male
6         0       1    male
7         0       3    male
8         1       3  female
9         1       2  female